import { clearXCookie, finishXOAuth } from '../../_lib/x-connect.js';
const esc = value => String(value || '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[char]);
const page = (ok, title, message, username = '') => `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(title)} — نَسَق</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:#05070b;color:#f7fbff;font-family:Tahoma,sans-serif}main{width:min(620px,100%);padding:30px;border:1px solid #263649;border-radius:24px;background:#0a0e15}b{color:${ok ? '#73e7ff' : '#ff91a6'}}h1{font-size:34px}p{color:#9eabba;line-height:1.9}.account{padding:15px;border:1px solid #263649;border-radius:14px;color:#73e7ff}a{display:inline-block;margin-top:18px;padding:12px 18px;border-radius:13px;background:#73e7ff;color:#05070b;text-decoration:none;font-weight:800}</style></head><body><main><b>X OAuth</b><h1>${esc(title)}</h1><p>${esc(message)}</p>${username ? `<div class="account">@${esc(username)}</div>` : ''}<a href="/">الرجوع إلى نَسَق</a></main></body></html>`;
export default async function handler(req, res) {
  if (req.method !== 'GET') { res.statusCode = 405; return res.end('Method Not Allowed'); }
  res.setHeader('set-cookie', clearXCookie()); res.setHeader('cache-control', 'no-store'); res.setHeader('referrer-policy', 'no-referrer'); res.setHeader('x-frame-options', 'DENY'); res.setHeader('content-security-policy', "default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'"); res.setHeader('content-type', 'text/html; charset=utf-8');
  try { const url = new URL(req.url, 'https://nasq.local'); if (url.searchParams.get('error')) throw new Error('denied'); const result = await finishXOAuth(req, url.searchParams.get('code') || '', url.searchParams.get('state') || ''); res.statusCode = 200; res.end(page(true, 'تم ربط حساب X', 'صار حساب نَسَق متصلًا بالخادم بصورة مشفرة.', result.username)); }
  catch (error) { console.error('x_oauth_failed', error instanceof Error ? error.message : 'failed'); res.statusCode = 400; res.end(page(false, 'تعذر ربط حساب X', error?.message === 'wrong_x_account' ? 'سجّل الدخول بحساب @agentsworks4u ثم أعد المحاولة.' : 'تأكد من إعدادات OAuth والصلاحيات ثم أعد المحاولة.')); }
}
